# -*- coding: utf-8 -*-
"""starter_code_cse151b_comp (2) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQcw1qiP8DHZt3OR-sSvOb8sgkj4AEEp

# CSE 151B Competition — Starter Notebook

Welcome to the **CSE 151B Spring 2026 Math Reasoning Competition**!  
This notebook walks you through the full pipeline end-to-end:

1. Setting up the Python environment with `uv`
2. Loading the competition dataset
3. Running inference with **Qwen3-4B-Thinking** via vLLM (INT8 quantized)
4. Scoring responses against ground-truth answers
5. Saving results to JSONL for submission

The public dataset (`public.jsonl`) contains questions **with** answers so you can measure accuracy locally.  
The private test set used for the leaderboard does **not** include answers — for that, skip evaluation and submit the raw responses.

## 1. Environment Setup

We use [`uv`](https://github.com/astral-sh/uv) for fast, reproducible package management.

The steps below:
1. Install `uv` into `~/.local/bin`
2. Create a virtual environment at `.venv/`
3. Install all required packages (This might take a while)

> **After running this cell, restart the kernel** so that the newly installed packages (especially `vllm` and `transformers`) are picked up by the current Python session.

### Comment Out the cell below after first installation.
"""

# !python -m pip install sympy numpy transformers tqdm bitsandbytes antlr4-python3-runtime==4.11.1 ipykernel jupyter && pip install vllm==0.19.1 --extra-index-url https://download.vllm.ai/whl/cu121/

# print("Done. Restart the kernel before proceeding.")
# print("Selection process: on top right, click on current kernel '(ususally named python)' -> 'select another kernel' -> 'Jupyter Kernel' -> 'Python (cse151b)'.")

"""### Run the cell below every time to activate the installed environment."""

# activate venv after installation. This needs to be run everytime.
# !source ./.venv/bin/activate

# !sed -i 's/stdout_fd = sys.stdout.fileno()/stdout_fd = 1/g' \
#     /usr/local/lib/python3.12/dist-packages/vllm/utils/system_utils.py

# import re

# path = '/usr/local/lib/python3.12/dist-packages/vllm/utils/system_utils.py'

# with open(path, 'r') as f:
#     content = f.read()

# # Find and replace the suppress_stdout function
# old = 'def suppress_stdout():'
# new_func = '''def suppress_stdout():
#     yield
#     return
#     # patched for notebook compatibility
# '''

# # Find the function and replace everything until the next def/class
# import re
# content = re.sub(
#     r'def suppress_stdout\(\):.*?(?=\ndef |\nclass |\Z)',
#     new_func,
#     content,
#     flags=re.DOTALL
# )

# with open(path, 'w') as f:
#     f.write(content)

# print('Patched. New content around suppress_stdout:')
# idx = content.find('def suppress_stdout')
# print(content[idx:idx+200])

"""## 2. Imports & Configuration

All key settings are collected in one place.  
- `DATA_PATH` — public dataset with ground-truth answers (use this to measure accuracy)
- `OUTPUT_PATH` — where per-question results will be written
- `GPU_ID` — which GPU to use (update if your machine has a different device index)
- `MAX_TOKENS` — maximum tokens the model may generate per response
"""

import json
import os
os.environ["VLLM_WORKER_MULTIPROC_METHOD"] = "spawn"
os.environ["VLLM_USE_V1"] = "0"
# os.environ["HF_TOKEN"] = ""

# ── Configuration ─────────────────────────────────────────────────────────────
MODEL_ID = "astondu/qwen3-4b-sft-merged"
GPU_ID      = "0"                    # CUDA_VISIBLE_DEVICES
DATA_PATH   = "/content/private.jsonl"
OUTPUT_PATH = "results/raw_results.jsonl"
MAX_TOKENS  = 4000

os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID

import re
import sys
from pathlib import Path
from typing import Optional

from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from tqdm import tqdm

import vllm.utils.system_utils as su
import contextlib

import json
import csv

SYSTEM_PROMPT_MATH = (
    "You are an expert mathematician. Solve the problem step-by-step. Think concisely; do not over-explain your answer. "
    "Put your final answer inside \\boxed{}. "
    "If the problem has multiple sub-answers, separate them by commas inside a single \\boxed{}, "
    "e.g. \\boxed{3, 7}. "
    "Here is an example: Problem: What is 15% of 80?; Solution: 15% of 80 = 0.15 × 80 = 12; Answer: \\boxed{12} "
    "Once you think you have an answer, make sure to thoroughly double check to ensure you made no mistakes. "
    "If possible, take your answer and plug it into the original question to make sure everything is correct. "
    "If you suspect a mistake, start over until you get it right. "
    "Remember: output your final answer as \\boxed{your answer} and nothing after it."
)

SYSTEM_PROMPT_MCQ = (
    "You are an expert mathematician. Think concisely; do not over-explain your answer. "
    "Read the problem and the answer choices below, then select the single best answer. "
    "Output ONLY the letter of your chosen option inside \\boxed{}, e.g. \\boxed{C}."
    "Work through each answer choice systematically. Eliminate obviously wrong options first, then verify your chosen answer. "
    "Once you think you have an answer, make sure to thoroughly double check to ensure you made no mistakes. "
    "If possible, take your answer and plug it into the original question to make sure everything is correct. "
    "If you suspect a mistake, start over until you get it right. "
    "Remember: output your final answer as \\boxed{your answer} and nothing after it."
)

"""## 3. Load the Dataset

The dataset is stored as newline-delimited JSON (`.jsonl`). Each line is one question with the following fields:

| Field | Description |
|---|---|
| `id` | Unique question identifier |
| `question` | Problem statement |
| `options` | List of answer choices — present for **MCQ**, absent for **free-form** |
| `answer` | Ground-truth answer (letter for MCQ, value/list for free-form) |
"""

def load_data():
    data = [json.loads(line) for line in open(DATA_PATH)]

    n_mcq  = sum(bool(d.get("options")) for d in data)
    n_free = sum(not d.get("options")   for d in data)
    print(f"Loaded {len(data)} questions  ({n_mcq} MCQ, {n_free} free-form)")

    # Preview one MCQ and one free-form item
    # mcq_sample  = next(d for d in data if d.get("options"))
    # free_sample = next(d for d in data if not d.get("options"))

    # print("\n── MCQ sample ──")
    # print(json.dumps(mcq_sample, indent=2))
    # print("\n── Free-form sample ──")
    # print(json.dumps(free_sample, indent=2))
    return data

"""## 4. Prompt Construction

We use two system prompts depending on the question type:

- **MCQ** — the model must select the best answer letter and wrap it in `\boxed{}`
- **Free-form** — the model solves step-by-step and puts the final answer in `\boxed{}`

`build_prompt()` returns the appropriate `(system, user)` pair for each item.
"""


def build_prompt(question: str, options: Optional[list]) -> tuple[str, str]:
    """Return (system_prompt, user_prompt) for a question."""
    if options:
        labels    = [chr(65 + i) for i in range(len(options))]
        opts_text = "\n".join(f"{lbl}. {opt.strip()}" for lbl, opt in zip(labels, options))
        return SYSTEM_PROMPT_MCQ, f"{question}\n\nOptions:\n{opts_text}"
    return SYSTEM_PROMPT_MATH, question


# Verify with samples
# for label, item in [("MCQ", mcq_sample), ("Free-form", free_sample)]:
#     sys_p, usr_p = build_prompt(item["question"], item.get("options"))
#     print(f"── {label} user prompt (first 200 chars) ──")
#     print(usr_p[:200], "...\n")

"""## 5. Load Model with vLLM (for general case, vLLM is faster)

We load **Qwen3-4B-Thinking-2507** with **INT8 quantization** via BitsAndBytes.  
Setting `load_format="bitsandbytes"` tells vLLM to apply on-the-fly INT8 weight quantization, roughly halving GPU memory usage compared to BF16.

Key parameters:
- `gpu_memory_utilization` — fraction of GPU VRAM reserved for the model and KV cache
- `max_model_len` — maximum sequence length (prompt + generation)
- `max_num_seqs` — maximum number of sequences processed in parallel
"""

# import vllm.utils.system_utils as su
# import contextlib

@contextlib.contextmanager
def _noop_suppress():
    yield

def load_vllm():
    su.suppress_stdout = _noop_suppress

    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    tokenizer.pad_token = tokenizer.eos_token

    llm = LLM(
        model=MODEL_ID,
        quantization="bitsandbytes",
        load_format="bitsandbytes",
        enable_prefix_caching=False,
        gpu_memory_utilization=0.85,
        max_model_len=8192,
        trust_remote_code=True,
        max_num_seqs=32,
        max_num_batched_tokens=8192,
        disable_log_stats=True,
    )

    sampling_params = SamplingParams(
        max_tokens=MAX_TOKENS,
        temperature=0.6,
        top_p=0.95,
        top_k=20,
        min_p=0.0,
        presence_penalty=0.0,
        repetition_penalty=1.0,
    )

    print("Model loaded.")
    return tokenizer, llm, sampling_params

"""## 6. Generate Responses

We format every question into a chat-template prompt, then call `llm.generate()` in one batched pass.  
vLLM handles batching and scheduling internally — no manual batching needed.

### Generate with vLLM
"""

# import json
# from tqdm import tqdm
def gen_responses():
    tokenizer, llm, sampling_params = load_vllm()
    os.makedirs("results", exist_ok=True)

    # Load already completed IDs for resuming
    completed_ids = set()
    try:
        with open(OUTPUT_PATH) as f:
            for line in f:
                completed_ids.add(json.loads(line)["id"])
        print(f"Resuming: {len(completed_ids)} already completed.")
    except FileNotFoundError:
        pass

    # Filter remaining
    data = load_data()
    remaining_data = [item for item in data if item.get("id") not in completed_ids]
    remaining_prompts = []
    for item in remaining_data:
        system, user = build_prompt(item["question"], item.get("options"))
        prompt_text = tokenizer.apply_chat_template(
            [{"role": "system", "content": system},
            {"role": "user",   "content": user}],
            tokenize=False,
            add_generation_prompt=True,
        )
        remaining_prompts.append(prompt_text)

    print(f"Generating responses for {len(remaining_data)} questions...")

    # Generate and save in batches
    BATCH_SIZE = 25

    with open(OUTPUT_PATH, "a") as f:
        for i in tqdm(range(0, len(remaining_data), BATCH_SIZE), desc="Batches"):
            batch_data    = remaining_data[i:i+BATCH_SIZE]
            batch_prompts = remaining_prompts[i:i+BATCH_SIZE]

            try:
                outputs = llm.generate(batch_prompts, sampling_params=sampling_params)
                for item, output in zip(batch_data, outputs):
                    response = output.outputs[0].text.strip()
                    f.write(json.dumps({"id": item.get("id"), "response": response}) + "\n")
                f.flush()
                print(f"Saved batch {i//BATCH_SIZE + 1}, total saved: {i + len(batch_data)}")
            except Exception as e:
                print(f"Batch {i//BATCH_SIZE + 1} failed: {e}")
                # Save empty responses for failed batch so we can track what failed
                for item in batch_data:
                    f.write(json.dumps({"id": item.get("id"), "response": ""}) + "\n")
                f.flush()

    print(f"\nDone. Results saved to {OUTPUT_PATH}")

    # Preview first 3
    all_results = [json.loads(l) for l in open(OUTPUT_PATH)]
    for r in all_results[:3]:
        print(f"\n── Response id={r['id']} ──")
        print(r['response'][:400])


def to_csv():
    INPUT_FILE = OUTPUT_PATH
    OUTPUT_FILE = "submission.csv"

    with open(INPUT_FILE, "r", encoding="utf-8") as fin, \
        open(OUTPUT_FILE, "w", encoding="utf-8", newline="") as fout:

        writer = csv.writer(
            fout,
            quoting=csv.QUOTE_ALL,  # safely handles commas, quotes, newlines
        )

        writer.writerow(["id", "response"])

        for line in fin:
            line = line.strip()
            if not line:
                continue

            record = json.loads(line)

            writer.writerow([
                record["id"],
                record["response"],
            ])

    print(f"Wrote {OUTPUT_FILE}")

def run_inference():
    gen_responses()
    to_csv()

if __name__ == "__main__":
    run_inference()